version: "3.9"

services:

  #rabbitmq container service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - "15672:15672"
    - "5672:5672"

  
  # sql server container service
  database:
    image: postgres:15-alpine
    container_name: postgres-server
    hostname: postgres
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_USER=fantoSama"
    - "POSTGRES_PASSWORD=f@nto237(!)" 
    - "POSTGRES_DB=OrderDb"   
    volumes: 
    - "../database:/var/lib/postgresql/data"
    restart: always

# database management tool
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080


