#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim AS base
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libexpat1
COPY --from=ubuntu20-dotnet6-opencv4.5.3 /usr/lib /usr/lib
COPY --from=ubuntu20-dotnet6-opencv4.5.3 /lib /lib

FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim AS build
WORKDIR /src
COPY ["FaceProcessApi/FaceProcessApi.csproj", "src/FaceProcessApi/"]
COPY ["SharedLib/SharedLib.csproj", "SharedLib/"]
RUN dotnet restore "src/FaceProcessApi/FaceProcessApi.csproj"
COPY . .
WORKDIR "/src/FaceProcessApi"
RUN dotnet build "FaceProcessApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FaceProcessApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FaceProcessApi.dll"]